config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :podcasts do
    resources :episodes, except: [:index]
  end

  get '/*slug', to: 'landing#show', constraints: ->(req) { !req.path.starts_with?('/rails') }

  root 'landing#show'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/episode.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: episodes
#
#  id          :bigint           not null, primary key
#  description :string           default(""), not null
#  explicit    :boolean          default(FALSE), not null
#  guid        :uuid             not null
#  keywords    :string           default(""), not null
#  pub_date    :datetime         not null
#  title       :string           default(""), not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  podcast_id  :bigint
#
# Indexes
#
#  index_episodes_on_podcast_id  (podcast_id)
#
# Foreign Keys
#
#  fk_rails_...  (podcast_id => podcasts.id)
#
class Episode < ApplicationRecord
  belongs_to :podcast

  has_one_attached :image
  has_one_attached :audio_file

  validates :title, :description, :keywords, :pub_date, presence: true

  # TODO: Add validation for file types in image and audio_file attachments
end

app/models/podcast.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: podcasts
#
#  id                  :bigint           not null, primary key
#  apple_podcasts_url  :string           default(""), not null
#  author              :string           not null
#  category            :string           not null
#  channel_type        :integer          not null
#  description         :text             not null
#  email               :string           default(""), not null
#  explicit            :boolean          default(FALSE), not null
#  google_podcasts_url :string           default(""), not null
#  language            :string           not null
#  limit               :integer
#  link                :string
#  slug                :string           default(""), not null
#  spotify_url         :string           default(""), not null
#  subcategory         :string
#  target_countries    :string           is an Array
#  title               :string           not null
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#
# Indexes
#
#  index_podcasts_on_slug  (slug) UNIQUE
#
class Podcast < ApplicationRecord
  validates :author, :channel_type, :category, :description, :email, :language, :target_countries,
            :title, :link, presence: true
  validates :slug, uniqueness: true
  validates :apple_podcasts_url, :google_podcasts_url, :spotify_url, url: { allow_blank: true }

  enum channel_type: {
    episodic: 0,
    serial: 1
  }

  has_one_attached :image

  # TODO: Add validation for file types in image attachment

  has_many :episodes
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Analytics

  before_action :authenticate

  private

  def authenticate
    return unless request.format != Mime[:rss]

    http_basic_authenticate_or_request_with(
      name: ENV.fetch('HTTP_BASIC_AUTH_NAME'),
      password: ENV.fetch('HTTP_BASIC_AUTH_PASSWORD')
    )
  end
end

app/controllers/concerns/analytics.rb
# frozen_string_literal: true

module Analytics
  extend ActiveSupport::Concern

  included do
    after_action :log
  end

  private

  def data
    {
      path: request.path,
      query_string: request.query_string,
      referrer: request.referrer,
      format: request.format.to_s,
      ip: request.remote_ip,
      user_agent: request.user_agent,
      method: request.method
    }
  end

  def log
    logger.unknown { "podcastfeeder-analytics=#{data.to_json}" }
  end
end

app/controllers/episodes_controller.rb
# frozen_string_literal: true

class EpisodesController < ApplicationController
  before_action :set_episode, only: %i[show edit update destroy]
  before_action :set_podcast

  # GET /episodes/1
  def show; end

  # GET /episodes/new
  def new
    @episode = Episode.new
  end

  # GET /episodes/1/edit
  def edit; end

  # POST /episodes
  def create
    @episode = Episode.new(episode_params.merge(guid: SecureRandom.uuid, podcast: @podcast))

    if @episode.save
      @episode.audio_file.analyze
      redirect_to @podcast, notice: 'Episode was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /episodes/1
  def update
    if @episode.update(episode_params)
      redirect_to @podcast, notice: 'Episode was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /episodes/1
  def destroy
    @episode.destroy
    redirect_to @podcast, notice: 'Episode was successfully destroyed.'
  end

  private

  def set_episode
    @episode = EpisodePresenter.new(
      Episode.find(params[:id])
    )
  end

  def set_podcast
    @podcast = Podcast.find(params[:podcast_id])
  end

  def episode_params
    params.require(:episode).permit(
      :audio_file,
      :description,
      :explicit,
      :guid,
      :image,
      :keywords,
      :pub_date,
      :title
    )
  end
end

app/controllers/landing_controller.rb
# frozen_string_literal: true

class LandingController < ApplicationController
  layout 'landing'

  skip_before_action :authenticate

  def show
    @podcast = Podcast.find_by!(slug: slug)
    @episodes = EpisodePresenter.all(
      @podcast.episodes.order(pub_date: :desc)
    )
  end

  private

  def slug
    params[:slug] || ''
  end
end

app/controllers/podcasts_controller.rb
# frozen_string_literal: true

class PodcastsController < ApplicationController
  before_action :set_podcast, only: %i[show edit update destroy]

  # GET /podcasts
  def index
    @podcasts = Podcast.all
  end

  # GET /podcasts/1
  def show
    @episodes = EpisodePresenter.all(
      @podcast.episodes.order(pub_date: :desc)
    )
  end

  # GET /podcasts/new
  def new
    @podcast = Podcast.new
  end

  # GET /podcasts/1/edit
  def edit; end

  # POST /podcasts
  def create
    @podcast = Podcast.new(processed_params)

    if @podcast.save
      redirect_to @podcast, notice: 'Podcast was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /podcasts/1
  def update
    if @podcast.update(processed_params)
      redirect_to @podcast, notice: 'Podcast was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /podcasts/1
  def destroy
    @podcast.destroy
    redirect_to podcasts_url, notice: 'Podcast was successfully destroyed.'
  end

  private

  def set_podcast
    @podcast = PodcastPresenter.new(
      Podcast.find(params[:id])
    )
  end

  def podcast_params
    params.require(:podcast).permit(
      :title,
      :description,
      :language,
      :author,
      :email,
      :explicit,
      :category,
      :channel_type,
      :limit,
      :link,
      :subcategory,
      :target_countries,
      :image,
      :apple_podcasts_url,
      :google_podcasts_url,
      :spotify_url
    )
  end

  def processed_params
    @processed_params ||= podcast_params.tap do |p|
      p[:target_countries] = p[:target_countries].split(' ')
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/application/_header.html.erb
<header class="px-3 py-2 bg-dark text-white">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" class="d-flex align-items-center my-2 my-lg-0 me-lg-auto text-white text-decoration-none">
        <%= content_for(:header_title) || "Podcast Feeder" %>
      </a>
    </div>
  </div>
</header>

app/views/application/_navigation.html.erb
<nav class="container py-2">
  <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
    <% unless request.path == root_path %>
      <%= link_to "Go back", :back %>
    <% end %>
  </div>
</nav>

app/views/episodes/_episode.html.erb
<div class="card mb-3" id="episode-<%= episode.id %>">
  <% if episode.image.attached? %>
    <%= image_tag episode.image, class: 'card-img-top' %>
  <% else %>
    <p class="badge badge-light">No image attached</p>
  <% end %>

  <div class="card-body">
    <p>
      <strong>Title:</strong>
      <%= episode.title %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= episode.description %>
    </p>

    <p>
      <strong>Audio:</strong>
    </p>
    <% if episode.audio_file.attached? %>
      <p><%= link_to polymorphic_url(episode.audio_file), polymorphic_url(episode.audio_file), { target: :_blank } %></p>
    <% else %>
      <p class="badge badge-light">No audio file attached</p>
    <% end %>

    <p>
      <strong>Duration:</strong>
      <%= episode.duration %> seconds
    </p>

    <p>
      <strong>Guid:</strong>
      <%= episode.guid %>
    </p>

    <p>
      <strong>Pub date:</strong>
      <%= episode.pub_date %>
    </p>

    <p>
      <strong>Explicit:</strong>
      <%= episode.explicit %>
    </p>

    <p>
      <strong>Keywords:</strong>
      <%= episode.keywords %>
    </p>

    <%= link_to 'Edit', edit_podcast_episode_path(@podcast, episode), class: 'btn btn-primary' %>
    <td><%= link_to 'Destroy', [@podcast, episode], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-light' %></td>
  </div>
</div>

app/views/episodes/_form.html.erb
<%= simple_form_for [@podcast, @episode] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :audio_file %>
    <%= f.input :image %>
    <%= f.input :pub_date %>
    <%= f.input :explicit %>
    <%= f.input :keywords %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/episodes/edit.html.erb
<h1>Editing Episode</h1>

<%= render 'form', episode: @episode %>

<%= link_to 'Show', [@podcast, @episode], class: 'btn btn-light' %>

app/views/episodes/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @podcast.title %> - Episodes</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Pub date</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @episodes.each do |episode| %>
      <tr>
        <td><%= l episode.pub_date, format: :long %></td>
        <td><%= episode.title %></td>
        <td><%= link_to 'Show', [@podcast, episode] %></td>
        <td><%= link_to 'Edit', edit_podcast_episode_path(@podcast, episode) %></td>
        <td><%= link_to 'Destroy', [@podcast, episode], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Episode', new_podcast_episode_path(@podcast), class: 'btn btn-primary' %>

app/views/episodes/new.html.erb
<h1>New Episode</h1>

<%= render 'form', episode: @episode %>

app/views/landing/show.html.erb
<body class="min-h-screen min-w-screen diagonal-lines bg-black text-gray-200">
  <div class="flex flex-col justify-center my-80">
    <div class="mx-auto my-4 static">
      <svg xmlns="http://www.w3.org/2000/svg" class="h-72 w-72 absolute mix-blend-overlay right-0" viewBox="0 0 20 20" fill="currentColor">
        <path fill-rule="evenodd" d="M7 4a3 3 0 016 0v4a3 3 0 11-6 0V4zm4 10.93A7.001 7.001 0 0017 8a1 1 0 10-2 0A5 5 0 015 8a1 1 0 00-2 0 7.001 7.001 0 006 6.93V17H6a1 1 0 100 2h8a1 1 0 100-2h-3v-2.07z" clip-rule="evenodd" />
      </svg>
    </div>
    <div class="container mx-auto">
      <h1 class="font-serif text-4xl sm:text-6xl md:text-7xl h-20 text-center font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-red-500 to-yellow-300"><%= @podcast.title %></h1>
      <p class="font-sans text-center text-gray-400 mt-4"><%= @podcast.description %></p>
      <p class="text-center mt-2 text-gray-400">
        <% external_link_class = "hover:text-white" %>
        <%= link_to 'Apple Podcasts', @podcast.apple_podcasts_url, class: external_link_class, target: :_blank %> |
        <%= link_to 'Google Podcasts', @podcast.google_podcasts_url, class: external_link_class, target: :_blank %> |
        <%= link_to 'Spotify', @podcast.spotify_url, class: external_link_class, target: :_blank %>
      </p>
    </div>
  </div>

  <div class="container mx-auto grid grid-cols-1 gap-12 md:grid-cols-2">

    <% @episodes.each do |episode| %>
      <div class="flex flex-col justify-between bg-gray-800 rounded">
        <p class="p-4 morphing-diamonds font-bold"><%= episode.title %></p>
        <div class="flex-grow flex flex-col justify-between p-4">
          <p class="pb-4"><%= episode.description %></p>
          <div class="pb-4">
            <% if episode.audio_file.attached? %>
              <button class="rounded-full py-2 px-8 bg-yellow-300 text-black"
                      data-audio-src="<%= polymorphic_url(episode.audio_file) %>"
                >
                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 inline" viewBox="0 0 20 20" fill="currentColor">
                  <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM9.555 7.168A1 1 0 008 8v4a1 1 0 001.555.832l3-2a1 1 0 000-1.664l-3-2z" clip-rule="evenodd" />
                </svg>
                Reproducir
              </button>
            <% end %>
          </div>
          <p><%= l episode.object.pub_date, format: '%B %-d, %Y' %></p>
        </div>
      </div>
    <% end %>

  </div>

  <div class="flex flex-col justify-center my-32">
    <div class="mx-auto">
      <div class="circle h-32 w-32 bg-gray-800 rounded-full flex flex-col justify-center mix-blend-exclusion">
        <svg xmlns="http://www.w3.org/2000/svg" class="mx-auto h-14 w-14 text-black" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M7 4a3 3 0 016 0v4a3 3 0 11-6 0V4zm4 10.93A7.001 7.001 0 0017 8a1 1 0 10-2 0A5 5 0 015 8a1 1 0 00-2 0 7.001 7.001 0 006 6.93V17H6a1 1 0 100 2h8a1 1 0 100-2h-3v-2.07z" clip-rule="evenodd" />
        </svg>
      </div>
    </div>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Podcast Feeder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render 'header' %>
    <%= render 'navigation' %>
    <main class="container py-3">
      <% if flash[:notice] %>
        <div class="alert alert-success"><%= flash[:notice] %></div>
      <% elsif flash[:alert] %>
        <div class="alert alert-danger"><%= flash[:alert] %></div>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @podcast.title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'landing', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'landing', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <%= yield %>
</html>

app/views/podcasts/_form.html.erb
<%= simple_form_for(@podcast) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :slug %>
    <%= f.input :description %>
    <%= f.input :image %>
    <%= f.input :link %>
    <%= f.input :language %>
    <%= f.input :author %>
    <%= f.input :email %>
    <%= f.input :explicit %>
    <%= f.input :category %>
    <%= f.input :subcategory %>
    <%= f.input :channel_type, collection: Podcast.channel_types.keys %>
    <%= f.input :limit %>
    <%= f.input :target_countries %>

    <%= f.input :spotify_url %>
    <%= f.input :apple_podcasts_url %>
    <%= f.input :google_podcasts_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/podcasts/edit.html.erb
<h1>Editing Podcast</h1>

<%= render 'form', podcast: @podcast %>

<%= link_to 'Show', @podcast, class: 'btn btn-light' %>

app/views/podcasts/index.html.erb
<h1>Podcasts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @podcasts.each do |podcast| %>
      <tr>
        <td><%= podcast.title %></td>
        <td><%= podcast.description %></td>
        <td><%= link_to 'Show', podcast %></td>
        <td><%= link_to 'Edit', edit_podcast_path(podcast) %></td>
        <td><%= link_to 'Destroy', podcast, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Podcast', new_podcast_path, class: 'btn btn-primary' %>

app/views/podcasts/new.html.erb
<h1>New Podcast</h1>

<%= render 'form', podcast: @podcast %>

app/views/podcasts/show.html.erb
<h1><%= @podcast.title %></h1>

<div class="row">
  <div class="col-lg-4 col-sm-12">
    <p>
      <strong>Description:</strong>
      <%= @podcast.description %>
    </p>

    <p>
      <strong>Image:</strong>
    </p>
    <% if @podcast.image.attached? %>
      <%= image_tag @podcast.image, class: 'img-thumbnail w-100 mb-3' %>
    <% else %>
      <p class="badge badge-light">No image attached</p>
    <% end %>

    <p>
      <strong>Link:</strong>
      <%= link_to @podcast.link, @podcast.link %>
    </p>

    <p>
      <strong>Language:</strong>
      <%= @podcast.language %>
    </p>

    <p>
      <strong>Author:</strong>
      <%= @podcast.author %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @podcast.email %>
    </p>

    <p>
      <strong>Explicit:</strong>
      <%= @podcast.explicit %>
    </p>

    <p>
      <strong>Category:</strong>
      <%= @podcast.category %> - <%= @podcast.subcategory %>
    </p>

    <p>
      <strong>Channel Type:</strong>
      <%= @podcast.channel_type %>
    </p>

    <p>
      <strong>Limit:</strong>
      <%= @podcast.limit %>
    </p>

    <p>
      <strong>Target countries:</strong>
      <%= @podcast.target_countries.join(', ') %>
    </p>

    <p>
      <strong>Apple Podcasts:</strong>
      <%= link_to @podcast.apple_podcasts_url, @podcast.apple_podcasts_url, target: :_blank %>
    </p>

    <p>
      <strong>Google Podcasts</strong>
      <%= link_to @podcast.google_podcasts_url, @podcast.google_podcasts_url, target: :_blank %>
    </p>

    <p>
      <strong>Spotify</strong>
      <%= link_to @podcast.spotify_url, @podcast.spotify_url, target: :_blank %>
    </p>

    <%= link_to 'Edit podcast', edit_podcast_path(@podcast), class: 'btn btn-primary' %>
  </div>

  <div class="col-lg-8 col-sm-12">
    <p><%= link_to 'Create episode', new_podcast_episode_path(@podcast), class: 'btn btn-primary' %></p>

    <% if @episodes.any? %>
      <%= render @episodes %>
    <% else %>
      <div class="alert alert-warning">Podcast does not have any episode</div>
    <% end %>
  </div>
</div>